builds:
  - id: fabricdirector
    goos:
      - linux
    goarch:
      - amd64

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"

nfpms:
  - id: fabricdirector
    package_name: fabricdirector
    file_name_template: "edged_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    vendor: Packetframe
    homepage: https://github.com/packetframe/fabricdirector
    maintainer: Nate Sales <nate@packetframe.com>
    description: Packetframe Fabric Director
    license: GNU GPL-3.0
    section: utils
    priority: extra
    formats:
      - deb
